extends SceneTree

func _init() -> void:
	var failures: Array[String] = []
	_check_file("res://project.godot", failures)
	_check_file("res://scenes/Main.tscn", failures)
	_check_file("res://scenes/Player.tscn", failures)
	_check_file("res://scenes/Enemy.tscn", failures)
	_check_file("res://scenes/BoyfriendCar.tscn", failures)
	_check_file("res://scripts/autoload/game_manager.gd", failures)
	_check_file("res://scripts/autoload/dialogue_manager.gd", failures)
	_check_file("res://scripts/main.gd", failures)
	_check_file("res://scripts/player.gd", failures)
	_check_file("res://scripts/enemy_chase.gd", failures)
	_check_file("res://scripts/spray_controller.gd", failures)
	_check_file("res://scripts/trigger_event.gd", failures)
	_check_file("res://scripts/convenience_store_door.gd", failures)
	_check_file("res://scripts/boyfriend_car.gd", failures)
	_check_file("res://tools/validate_extended_flow.gd", failures)
	_check_file("res://tools/validate_map_bounds.gd", failures)
	_check_file("res://data/dialogues.json", failures)
	_check_file("res://data/game_config.json", failures)
	_check_file("res://asset_manifest.lock.json", failures)
	_check_file("res://assets/source/characters/hero_spritesheet.webp", failures)
	_check_file("res://assets/source/characters/boyfriend_spritesheet.webp", failures)
	_check_file("res://assets/source/vehicles/potato-style-car-front-3q.png", failures)
	_check_file("res://assets/source/creatures/nightmare-creature-single-256h.png", failures)
	_check_file("res://assets/source/creatures/nightmare-creature-motion-atlas.png", failures)
	_check_file("res://assets/source/manifests/nightmare_creature_motion_manifest.json", failures)
	_check_file("res://assets/source/buildings/convenience-store-potato-style.png", failures)
	_check_file("res://assets/source/animals/baekgu-protector-single.png", failures)
	_check_file("res://assets/source/animals/baekgu-protector-motion-atlas.png", failures)
	_check_file("res://assets/source/animals/baekgu-protector-motion-atlas.webp", failures)
	_check_file("res://assets/source/animals/baekgu-protector-motion-manifest.json", failures)
	_check_file("res://assets/source/animals/idle-alert.png", failures)
	_check_file("res://assets/source/animals/run-to-protect.png", failures)
	_check_file("res://assets/source/animals/guard-block.png", failures)
	_check_file("res://assets/source/animals/bite-lunge.png", failures)
	_check_file("res://assets/source/animals/bark-warning.png", failures)
	_check_file("res://assets/source/animals/hurt-recover.png", failures)
	_check_file("res://assets/source/animals/key-cat-single.png", failures)
	_check_file("res://assets/source/environment/bush-maze-tileset.png", failures)
	_check_file("res://assets/source/environment/factory-tileset-obstacles.png", failures)
	_check_file("res://assets/source/environment/factory-backside-background.png", failures)
	_check_file("res://assets/source/environment/flashlight-beam-texture.png", failures)
	_check_file("res://assets/source/environment/flashlight-dust-overlay.png", failures)
	_check_file("res://assets/source/environment/flashlight-bush-reveal.png", failures)
	_check_file("res://assets/source/environment/store-reversal-cutscene-sheet.png", failures)
	_check_file("res://assets/source/environment/key-cat-animation-spritesheet.png", failures)
	_check_file("res://assets/source/environment/convenience-store-prop-sheet.png", failures)
	_check_file("res://assets/source/environment/environment_asset_manifest.json", failures)
	_check_resource_load("res://scenes/Main.tscn", failures)
	_check_resource_load("res://scenes/Player.tscn", failures)
	_check_resource_load("res://scenes/Enemy.tscn", failures)
	_check_resource_load("res://scenes/BoyfriendCar.tscn", failures)
	_check_resource_load("res://assets/source/vehicles/potato-style-car-front-3q.png", failures)
	_check_resource_load("res://assets/source/creatures/nightmare-creature-single-256h.png", failures)
	_check_resource_load("res://assets/source/creatures/nightmare-creature-motion-atlas.png", failures)
	_check_resource_load("res://assets/source/buildings/convenience-store-potato-style.png", failures)
	_check_resource_load("res://assets/source/animals/baekgu-protector-single.png", failures)
	_check_resource_load("res://assets/source/animals/baekgu-protector-motion-atlas.png", failures)
	_check_resource_load("res://assets/source/animals/baekgu-protector-motion-atlas.webp", failures)
	_check_resource_load("res://assets/source/animals/idle-alert.png", failures)
	_check_resource_load("res://assets/source/animals/run-to-protect.png", failures)
	_check_resource_load("res://assets/source/animals/guard-block.png", failures)
	_check_resource_load("res://assets/source/animals/bite-lunge.png", failures)
	_check_resource_load("res://assets/source/animals/bark-warning.png", failures)
	_check_resource_load("res://assets/source/animals/hurt-recover.png", failures)
	_check_resource_load("res://assets/source/environment/bush-maze-tileset.png", failures)
	_check_resource_load("res://assets/source/environment/factory-tileset-obstacles.png", failures)
	_check_resource_load("res://assets/source/environment/factory-backside-background.png", failures)
	_check_resource_load("res://assets/source/environment/flashlight-beam-texture.png", failures)
	_check_resource_load("res://assets/source/environment/flashlight-dust-overlay.png", failures)
	_check_resource_load("res://assets/source/environment/flashlight-bush-reveal.png", failures)
	_check_resource_load("res://assets/source/environment/store-reversal-cutscene-sheet.png", failures)
	_check_resource_load("res://assets/source/environment/key-cat-animation-spritesheet.png", failures)
	_check_resource_load("res://assets/source/environment/convenience-store-prop-sheet.png", failures)
	_check_resource_load("res://scripts/player.gd", failures)
	_check_resource_load("res://scripts/enemy_chase.gd", failures)
	_check_resource_load("res://scripts/autoload/audio_manager.gd", failures)
	_check_json("res://data/dialogues.json", failures)
	_check_json("res://data/game_config.json", failures)
	_check_json("res://assets/source/environment/environment_asset_manifest.json", failures)
	_check_text_contains("res://scripts/player.gd", "CELL_SIZE := Vector2(192, 208)", failures)
	_check_text_contains("res://scripts/player.gd", "CHARACTER_VISUAL_SCALE", failures)
	_check_text_contains("res://scripts/player.gd", "INTERACTION_DETECTOR_RADIUS := 82.0", failures)
	_check_text_contains("res://scripts/player.gd", "nearby_interactables", failures)
	_check_text_contains("res://scripts/player.gd", "_refresh_current_interactable", failures)
	_check_text_contains("res://scripts/player.gd", "set_flashlight_enabled", failures)
	_check_text_contains("res://scripts/player.gd", "FlashlightCone", failures)
	_check_text_contains("res://scripts/player.gd", "FlashlightDust", failures)
	_check_text_contains("res://scripts/player.gd", "flashlight-beam-texture.png", failures)
	_check_text_contains("res://scripts/player.gd", "flashlight-dust-overlay.png", failures)
	_check_text_contains("res://scripts/player.gd", "CanvasItemMaterial.BLEND_MODE_ADD", failures)
	_check_text_contains("res://scripts/player.gd", "InputMap.add_action", failures)
	_check_text_contains("res://scripts/player.gd", "Input.get_action_strength", failures)
	_check_text_contains("res://scripts/boyfriend_car.gd", "CAR_VISUAL_SCALE", failures)
	_check_text_contains("res://scripts/boyfriend_car.gd", "potato-style-car-front-3q.png", failures)
	_check_text_contains("res://scripts/enemy_chase.gd", "nightmare-creature-motion-atlas.png", failures)
	_check_text_contains("res://scripts/enemy_chase.gd", "CELL_SIZE := Vector2(448, 640)", failures)
	_check_text_contains("res://scripts/enemy_chase.gd", "charge-towards", failures)
	_check_text_contains("res://scripts/enemy_chase.gd", "collision_layer = 0", failures)
	_check_text_contains("res://scripts/enemy_chase.gd", "CatchArea", failures)
	_check_text_contains("res://scripts/main.gd", "convenience-store-potato-style.png", failures)
	_check_text_contains("res://scripts/main.gd", "FINAL_CHASE_START_GAP := 320.0", failures)
	_check_text_contains("res://scripts/main.gd", "_get_final_chase_escape_position", failures)
	_check_text_contains("res://scripts/main.gd", "StreetlightLampHousing", failures)
	_check_text_contains("res://scripts/main.gd", "StreetlightLightPool", failures)
	_check_text_absent("res://scripts/main.gd", "\"OldHouse\", Vector2(-105, -250), Vector2(110, 85), Color(0.13, 0.10, 0.09, 1.0), true", failures)
	_check_text_contains("res://scripts/main.gd", "_add_store_lighting", failures)
	_check_text_contains("res://scripts/main.gd", "_add_store_clues", failures)
	_check_text_contains("res://scripts/main.gd", "_add_payphone", failures)
	_check_text_contains("res://scripts/main.gd", "_add_store_clue_glints", failures)
	_check_text_contains("res://scripts/main.gd", "store_payphone", failures)
	_check_text_contains("res://scripts/main.gd", "영수증 확인", failures)
	_check_text_contains("res://scripts/main.gd", "streetlight_glimpse", failures)
	_check_text_contains("res://scripts/main.gd", "run_streetlight_glimpse", failures)
	_check_text_contains("res://scripts/main.gd", "_run_tension_event", failures)
	_check_text_contains("res://scripts/main.gd", "FACTORY_CHASE_DURATION := 20.0", failures)
	_check_text_contains("res://scripts/main.gd", "Baekgu", failures)
	_check_text_contains("res://scripts/main.gd", "baekgu-protector-motion-atlas.png", failures)
	_check_text_contains("res://scripts/main.gd", "BAEKGU_CELL_SIZE := Vector2i(448, 640)", failures)
	_check_text_contains("res://scripts/main.gd", "BAEKGU_VISUAL_SCALE := 0.185", failures)
	_check_text_contains("res://scripts/main.gd", "BaekguRimLight", failures)
	_check_text_contains("res://scripts/main.gd", "TEXTURE_FILTER_LINEAR", failures)
	_check_text_contains("res://scripts/main.gd", "_build_baekgu_sprite_frames", failures)
	_check_text_contains("res://scripts/main.gd", "AtlasTexture.new()", failures)
	_check_text_contains("res://scripts/main.gd", "AnimatedSprite2D", failures)
	_check_text_contains("res://scripts/main.gd", "_show_baekgu_state", failures)
	_check_text_contains("res://scripts/main.gd", "BAEKGU_VISUAL_SCALE", failures)
	_check_text_contains("res://scripts/main.gd", "_add_world_bounds", failures)
	_check_text_contains("res://scripts/main.gd", "_add_outer_background", failures)
	_check_text_contains("res://scripts/main.gd", "WorldOuterBackdrop", failures)
	_check_text_contains("res://scripts/main.gd", "WorldFarLeftForestMass", failures)
	_check_text_contains("res://scripts/main.gd", "OuterRoadCrack", failures)
	_check_text_contains("res://scripts/main.gd", "HomeSouthHedge", failures)
	_check_text_contains("res://scripts/main.gd", "SafetyFenceRoadBlock", failures)
	_check_text_contains("res://scripts/main.gd", "UpperEscapeLeftBoundary", failures)
	_check_text_contains("res://scripts/main.gd", "RescueNorthRoadblock", failures)
	_check_text_contains("res://scripts/main.gd", "_add_roadside_detail_pass", failures)
	_check_text_contains("res://scripts/main.gd", "_add_store_detail_pass", failures)
	_check_text_contains("res://scripts/main.gd", "StoreShoppingBasket", failures)
	_check_text_contains("res://scripts/main.gd", "FactoryWarningStripe", failures)
	_check_text_contains("res://scripts/main.gd", "_add_bush_maze_area", failures)
	_check_text_contains("res://scripts/main.gd", "BushMazeFloor", failures)
	_check_text_contains("res://scripts/main.gd", "PowerBoxCase", failures)
	_check_text_contains("res://scripts/main.gd", "KeyCatSprite", failures)
	_check_text_contains("res://scripts/main.gd", "Vector2(64, -2148), Vector2(188, 38)", failures)
	_check_text_contains("res://scripts/main.gd", "BushMazePathWash", failures)
	_check_text_contains("res://scripts/main.gd", "BushMazeFlashlightReveal", failures)
	_check_text_contains("res://scripts/main.gd", "flashlight-bush-reveal.png", failures)
	_check_text_contains("res://scripts/main.gd", "_update_maze_reveal_sprites", failures)
	_check_text_contains("res://scripts/main.gd", "Vector2(86, 34)", failures)
	_check_text_contains("res://scripts/main.gd", "key-cat-single.png", failures)
	_check_text_contains("res://scripts/main.gd", "bush-maze-tileset.png", failures)
	_check_text_contains("res://scripts/main.gd", "factory-tileset-obstacles.png", failures)
	_check_text_contains("res://scripts/main.gd", "factory-backside-background.png", failures)
	_check_text_contains("res://scripts/main.gd", "store-reversal-cutscene-sheet.png", failures)
	_check_text_contains("res://scripts/main.gd", "key-cat-animation-spritesheet.png", failures)
	_check_text_contains("res://scripts/main.gd", "convenience-store-prop-sheet.png", failures)
	_check_text_contains("res://scripts/main.gd", "_add_sheet_cell", failures)
	_check_text_contains("res://scripts/main.gd", "_add_bush_maze_asset_pass", failures)
	_check_text_contains("res://scripts/main.gd", "_add_factory_backside_background_asset", failures)
	_check_text_contains("res://scripts/main.gd", "FactoryBacksideBackgroundAsset", failures)
	_check_text_contains("res://assets/source/environment/environment_asset_manifest.json", "flashlight-beam-texture.png", failures)
	_check_text_contains("res://assets/source/environment/environment_asset_manifest.json", "flashlight-dust-overlay.png", failures)
	_check_text_contains("res://assets/source/environment/environment_asset_manifest.json", "flashlight-bush-reveal.png", failures)
	_check_text_contains("res://scripts/main.gd", "FactoryMachineAssetA", failures)
	_check_text_contains("res://scripts/main.gd", "StorePropDoorMatAsset", failures)
	_check_text_contains("res://scripts/main.gd", "_build_key_cat_sprite_frames", failures)
	_check_text_contains("res://scripts/main.gd", "WrongKeyDroppedKeyDecal", failures)
	_check_text_contains("res://scripts/main.gd", "cat_clearing", failures)
	_check_text_contains("res://scripts/main.gd", "return_presence", failures)
	_check_text_contains("res://scripts/main.gd", "ReturnPresenceBlocker", failures)
	_check_text_contains("res://scripts/main.gd", "_add_factory_area", failures)
	_check_text_contains("res://scripts/main.gd", "FactoryExitBlocker", failures)
	_check_text_contains("res://scripts/main.gd", "FactoryExitGuideLight", failures)
	_check_text_contains("res://scripts/main.gd", "FactoryExitBeaconInner", failures)
	_check_text_contains("res://scripts/main.gd", "_update_factory_exit_guides", failures)
	_check_text_contains("res://scripts/main.gd", "Vector2(240, 135)", failures)
	_check_text_contains("res://scripts/main.gd", "factory_exit", failures)
	_check_text_contains("res://scripts/main.gd", "dog_intervention", failures)
	_check_text_contains("res://scripts/main.gd", "FACTORY_BACKSIDE", failures)
	_check_text_contains("res://scripts/main.gd", "run_factory_backside_escape", failures)
	_check_text_contains("res://scripts/main.gd", "_update_factory_exit_escape", failures)
	_check_text_absent("res://scripts/main.gd", "rescue_zone\", Vector2(0, -2225)", failures)
	_check_text_contains("res://scripts/spray_controller.gd", "manager.set_spray_uses(manager.spray_uses - 1)", failures)
	_check_text_contains("res://scripts/autoload/audio_manager.gd", "AudioStreamGenerator", failures)
	_check_text_contains("res://scripts/autoload/audio_manager.gd", "Bgm_EerieDrone", failures)
	_check_text_contains("res://scripts/autoload/audio_manager.gd", "set_bgm_intensity", failures)
	_check_text_contains("res://scripts/autoload/audio_manager.gd", "set_bgm_profile", failures)
	_check_text_contains("res://scripts/autoload/audio_manager.gd", "_next_chase_bgm_sample", failures)
	_check_text_contains("res://scripts/autoload/audio_manager.gd", "bgm_profile == \"chase\"", failures)
	_check_text_contains("res://scripts/autoload/audio_manager.gd", "_next_bush_maze_bgm_sample", failures)
	_check_text_contains("res://scripts/autoload/audio_manager.gd", "stream.buffer_length = 0.9", failures)
	_check_text_contains("res://scripts/autoload/audio_manager.gd", "grass_footstep", failures)
	_check_text_contains("res://scripts/autoload/audio_manager.gd", "_write_grass_footstep_sfx", failures)
	_check_text_contains("res://scripts/autoload/audio_manager.gd", "horror_footstep", failures)
	_check_text_contains("res://scripts/autoload/audio_manager.gd", "_write_horror_footstep_sfx", failures)
	_check_text_contains("res://scripts/autoload/audio_manager.gd", "sub_rumble", failures)
	_check_text_contains("res://scripts/autoload/audio_manager.gd", "bgm_phase_scrape", failures)
	_check_text_contains("res://scripts/autoload/audio_manager.gd", "rescue_honk", failures)
	_check_text_contains("res://scripts/autoload/audio_manager.gd", "bush_rustle", failures)
	_check_text_contains("res://scripts/autoload/audio_manager.gd", "phone_ring", failures)
	_check_text_contains("res://scripts/autoload/audio_manager.gd", "dog_bark", failures)
	_check_text_contains("res://scripts/autoload/audio_manager.gd", "metal_clang", failures)
	_check_text_contains("res://scripts/autoload/audio_manager.gd", "rescue_honk_far", failures)
	_check_text_contains("res://scripts/autoload/audio_manager.gd", "flashlight_pickup", failures)
	_check_text_contains("res://scripts/autoload/audio_manager.gd", "key_jingle", failures)
	_check_text_contains("res://scripts/autoload/audio_manager.gd", "cat_meow", failures)
	_check_text_contains("res://scripts/autoload/audio_manager.gd", "leaf_stinger", failures)
	_check_text_contains("res://scripts/autoload/audio_manager.gd", "store_door_lock_heavy", failures)
	_check_text_contains("res://scripts/autoload/audio_manager.gd", "car_impact_heavy", failures)
	_check_text_contains("res://scripts/autoload/audio_manager.gd", "player.stop()", failures)
	_check_text_contains("res://scripts/autoload/audio_manager.gd", "player.stream = stream", failures)
	_check_text_contains("res://scripts/autoload/game_manager.gd", "store_receipt", failures)
	_check_text_contains("res://scripts/autoload/game_manager.gd", "STORE_CLUE_IDS", failures)
	_check_text_contains("res://scripts/autoload/game_manager.gd", "STORE_CLUE_LABELS", failures)
	_check_text_contains("res://scripts/autoload/game_manager.gd", "_is_store_investigation_complete", failures)
	_check_text_contains("res://scripts/autoload/game_manager.gd", "_set_bgm_for_stage", failures)
	_check_text_contains("res://scripts/autoload/game_manager.gd", "set_bgm_profile(\"chase\")", failures)
	_check_text_contains("res://scripts/autoload/game_manager.gd", "문은 잊어", failures)
	_check_text_contains("res://scripts/autoload/game_manager.gd", "interaction_prompt_changed", failures)
	_check_text_contains("res://scripts/autoload/game_manager.gd", "set_interaction_prompt", failures)
	_check_text_contains("res://scripts/autoload/game_manager.gd", "FACTORY_CHASE_DURATION := 20", failures)
	_check_text_contains("res://scripts/autoload/game_manager.gd", "DOG_INTERVENTION", failures)
	_check_text_contains("res://scripts/autoload/game_manager.gd", "FACTORY_CHASE", failures)
	_check_text_contains("res://scripts/autoload/game_manager.gd", "finish_factory_timer", failures)
	_check_text_contains("res://scripts/autoload/game_manager.gd", "위쪽 파란 비상등 출구", failures)
	_check_text_contains("res://scripts/autoload/game_manager.gd", "FACTORY_BACKSIDE", failures)
	_check_text_contains("res://scripts/autoload/game_manager.gd", "BUSH_MAZE", failures)
	_check_text_contains("res://scripts/autoload/game_manager.gd", "WRONG_KEY_REVEAL", failures)
	_check_text_contains("res://scripts/autoload/game_manager.gd", "factory_exit_transition_started", failures)
	_check_text_contains("res://scripts/autoload/game_manager.gd", "start_factory_backside", failures)
	_check_text_contains("res://scripts/autoload/game_manager.gd", "pickup_flashlight", failures)
	_check_text_contains("res://scripts/autoload/game_manager.gd", "collect_cat_key", failures)
	_check_text_contains("res://scripts/autoload/game_manager.gd", "reveal_wrong_key", failures)
	_check_text_contains("res://scripts/main.gd", "run_wrong_key_reveal", failures)
	_check_text_contains("res://scripts/main.gd", "run_escape_driveaway", failures)
	_check_text_contains("res://scripts/hud.gd", "interaction_label", failures)
	_check_text_contains("res://data/dialogues.json", "store_footprints", failures)
	_check_text_contains("res://data/dialogues.json", "store_payphone", failures)
	_check_text_contains("res://data/dialogues.json", "store_clues_complete", failures)
	_check_text_contains("res://data/dialogues.json", "dog_intervention", failures)
	_check_text_contains("res://data/dialogues.json", "factory_hide", failures)
	_check_text_contains("res://data/dialogues.json", "factory_backside_escape", failures)
	_check_text_contains("res://data/dialogues.json", "flashlight_found", failures)
	_check_text_contains("res://data/dialogues.json", "cat_key_found", failures)
	_check_text_contains("res://data/dialogues.json", "wrong_key_reveal", failures)
	_check_text_contains("res://data/dialogues.json", "백구가 괴물의 앞을 가로막고", failures)
	_check_text_contains("res://tools/validate_extended_flow.gd", "EXTENDED_FLOW_OK", failures)
	_check_text_contains("res://tools/validate_extended_flow.gd", "start_dog_intervention", failures)
	_check_text_contains("res://tools/validate_extended_flow.gd", "factory_chase_seconds_left == manager.FACTORY_CHASE_DURATION", failures)
	_check_text_contains("res://tools/validate_extended_flow.gd", "FACTORY_CHASE_SPEED > main.player.walk_speed", failures)
	_check_text_contains("res://tools/validate_extended_flow.gd", "_factory_obstacle_count", failures)
	_check_text_contains("res://tools/validate_extended_flow.gd", "FACTORY_BACKSIDE", failures)
	_check_text_contains("res://tools/validate_extended_flow.gd", "factory exit overlap did not advance to backside", failures)
	_check_text_contains("res://tools/validate_map_bounds.gd", "MAP_BOUNDS_OK", failures)
	_check_text_absent("res://scripts/main.gd", "store_sensor", failures)
	_check_text_absent("res://scripts/main.gd", "SensorClueGlint", failures)
	_check_text_absent("res://scripts/autoload/game_manager.gd", "store_sensor", failures)
	_check_text_absent("res://data/dialogues.json", "\"store_sensor\"", failures)

	if failures.size() > 0:
		for failure in failures:
			print("VALIDATION_FAIL: ", failure)
		quit(1)
	print("VALIDATION_OK")
	quit(0)

func _check_file(path: String, failures: Array[String]) -> void:
	if not FileAccess.file_exists(path):
		failures.append("missing file: " + path)

func _check_resource_load(path: String, failures: Array[String]) -> void:
	var resource = load(path)
	if resource == null:
		failures.append("cannot load resource: " + path)

func _check_json(path: String, failures: Array[String]) -> void:
	if not FileAccess.file_exists(path):
		return
	var file := FileAccess.open(path, FileAccess.READ)
	if file == null:
		failures.append("cannot open json: " + path)
		return
	var parsed = JSON.parse_string(file.get_as_text())
	if parsed == null:
		failures.append("cannot parse json: " + path)

func _check_text_contains(path: String, needle: String, failures: Array[String]) -> void:
	if not FileAccess.file_exists(path):
		return
	var file := FileAccess.open(path, FileAccess.READ)
	if file == null:
		return
	if not file.get_as_text().contains(needle):
		failures.append("missing expected text in " + path + ": " + needle)

func _check_text_absent(path: String, needle: String, failures: Array[String]) -> void:
	if not FileAccess.file_exists(path):
		return
	var file := FileAccess.open(path, FileAccess.READ)
	if file == null:
		return
	if file.get_as_text().contains(needle):
		failures.append("unexpected text in " + path + ": " + needle)
