extends SceneTree

func _init() -> void:
	var failures: Array[String] = []
	_check_file("res://project.godot", failures)
	_check_file("res://scenes/Main.tscn", failures)
	_check_file("res://scenes/Player.tscn", failures)
	_check_file("res://scenes/Enemy.tscn", failures)
	_check_file("res://scenes/BoyfriendCar.tscn", failures)
	_check_file("res://scripts/autoload/game_manager.gd", failures)
	_check_file("res://scripts/autoload/dialogue_manager.gd", failures)
	_check_file("res://scripts/main.gd", failures)
	_check_file("res://scripts/player.gd", failures)
	_check_file("res://scripts/enemy_chase.gd", failures)
	_check_file("res://scripts/spray_controller.gd", failures)
	_check_file("res://scripts/trigger_event.gd", failures)
	_check_file("res://scripts/convenience_store_door.gd", failures)
	_check_file("res://scripts/boyfriend_car.gd", failures)
	_check_file("res://tools/validate_extended_flow.gd", failures)
	_check_file("res://tools/validate_map_bounds.gd", failures)
	_check_file("res://data/dialogues.json", failures)
	_check_file("res://data/game_config.json", failures)
	_check_file("res://asset_manifest.lock.json", failures)
	_check_file("res://assets/source/characters/hero_spritesheet.webp", failures)
	_check_file("res://assets/source/characters/boyfriend_spritesheet.webp", failures)
	_check_file("res://assets/source/vehicles/potato-style-car-front-3q.png", failures)
	_check_file("res://assets/source/creatures/nightmare-creature-single-256h.png", failures)
	_check_file("res://assets/source/creatures/nightmare-creature-motion-atlas.png", failures)
	_check_file("res://assets/source/manifests/nightmare_creature_motion_manifest.json", failures)
	_check_file("res://assets/source/buildings/convenience-store-potato-style.png", failures)
	_check_file("res://assets/source/animals/baekgu-protector-single.png", failures)
	_check_file("res://assets/source/animals/baekgu-protector-motion-atlas.png", failures)
	_check_file("res://assets/source/animals/baekgu-protector-motion-atlas.webp", failures)
	_check_file("res://assets/source/animals/baekgu-protector-motion-manifest.json", failures)
	_check_file("res://assets/source/animals/idle-alert.png", failures)
	_check_file("res://assets/source/animals/run-to-protect.png", failures)
	_check_file("res://assets/source/animals/guard-block.png", failures)
	_check_file("res://assets/source/animals/bite-lunge.png", failures)
	_check_file("res://assets/source/animals/bark-warning.png", failures)
	_check_file("res://assets/source/animals/hurt-recover.png", failures)
	_check_resource_load("res://scenes/Main.tscn", failures)
	_check_resource_load("res://scenes/Player.tscn", failures)
	_check_resource_load("res://scenes/Enemy.tscn", failures)
	_check_resource_load("res://scenes/BoyfriendCar.tscn", failures)
	_check_resource_load("res://assets/source/vehicles/potato-style-car-front-3q.png", failures)
	_check_resource_load("res://assets/source/creatures/nightmare-creature-single-256h.png", failures)
	_check_resource_load("res://assets/source/creatures/nightmare-creature-motion-atlas.png", failures)
	_check_resource_load("res://assets/source/buildings/convenience-store-potato-style.png", failures)
	_check_resource_load("res://assets/source/animals/baekgu-protector-single.png", failures)
	_check_resource_load("res://assets/source/animals/baekgu-protector-motion-atlas.png", failures)
	_check_resource_load("res://assets/source/animals/baekgu-protector-motion-atlas.webp", failures)
	_check_resource_load("res://assets/source/animals/idle-alert.png", failures)
	_check_resource_load("res://assets/source/animals/run-to-protect.png", failures)
	_check_resource_load("res://assets/source/animals/guard-block.png", failures)
	_check_resource_load("res://assets/source/animals/bite-lunge.png", failures)
	_check_resource_load("res://assets/source/animals/bark-warning.png", failures)
	_check_resource_load("res://assets/source/animals/hurt-recover.png", failures)
	_check_resource_load("res://scripts/player.gd", failures)
	_check_resource_load("res://scripts/enemy_chase.gd", failures)
	_check_resource_load("res://scripts/autoload/audio_manager.gd", failures)
	_check_json("res://data/dialogues.json", failures)
	_check_json("res://data/game_config.json", failures)
	_check_text_contains("res://scripts/player.gd", "CELL_SIZE := Vector2(192, 208)", failures)
	_check_text_contains("res://scripts/player.gd", "CHARACTER_VISUAL_SCALE", failures)
	_check_text_contains("res://scripts/player.gd", "INTERACTION_DETECTOR_RADIUS := 82.0", failures)
	_check_text_contains("res://scripts/player.gd", "nearby_interactables", failures)
	_check_text_contains("res://scripts/player.gd", "_refresh_current_interactable", failures)
	_check_text_contains("res://scripts/player.gd", "InputMap.add_action", failures)
	_check_text_contains("res://scripts/player.gd", "Input.get_action_strength", failures)
	_check_text_contains("res://scripts/boyfriend_car.gd", "CAR_VISUAL_SCALE", failures)
	_check_text_contains("res://scripts/boyfriend_car.gd", "potato-style-car-front-3q.png", failures)
	_check_text_contains("res://scripts/enemy_chase.gd", "nightmare-creature-motion-atlas.png", failures)
	_check_text_contains("res://scripts/enemy_chase.gd", "CELL_SIZE := Vector2(448, 640)", failures)
	_check_text_contains("res://scripts/enemy_chase.gd", "charge-towards", failures)
	_check_text_contains("res://scripts/enemy_chase.gd", "collision_layer = 0", failures)
	_check_text_contains("res://scripts/enemy_chase.gd", "CatchArea", failures)
	_check_text_contains("res://scripts/main.gd", "convenience-store-potato-style.png", failures)
	_check_text_contains("res://scripts/main.gd", "FINAL_CHASE_START_GAP := 320.0", failures)
	_check_text_contains("res://scripts/main.gd", "_get_final_chase_escape_position", failures)
	_check_text_contains("res://scripts/main.gd", "StreetlightLampHousing", failures)
	_check_text_contains("res://scripts/main.gd", "StreetlightLightPool", failures)
	_check_text_absent("res://scripts/main.gd", "\"OldHouse\", Vector2(-105, -250), Vector2(110, 85), Color(0.13, 0.10, 0.09, 1.0), true", failures)
	_check_text_contains("res://scripts/main.gd", "_add_store_lighting", failures)
	_check_text_contains("res://scripts/main.gd", "_add_store_clues", failures)
	_check_text_contains("res://scripts/main.gd", "_add_payphone", failures)
	_check_text_contains("res://scripts/main.gd", "_add_store_clue_glints", failures)
	_check_text_contains("res://scripts/main.gd", "store_payphone", failures)
	_check_text_contains("res://scripts/main.gd", "영수증 확인", failures)
	_check_text_contains("res://scripts/main.gd", "streetlight_glimpse", failures)
	_check_text_contains("res://scripts/main.gd", "run_streetlight_glimpse", failures)
	_check_text_contains("res://scripts/main.gd", "_run_tension_event", failures)
	_check_text_contains("res://scripts/main.gd", "FACTORY_CHASE_DURATION := 40.0", failures)
	_check_text_contains("res://scripts/main.gd", "Baekgu", failures)
	_check_text_contains("res://scripts/main.gd", "baekgu-protector-motion-atlas.png", failures)
	_check_text_contains("res://scripts/main.gd", "BAEKGU_CELL_SIZE := Vector2i(448, 640)", failures)
	_check_text_contains("res://scripts/main.gd", "_build_baekgu_sprite_frames", failures)
	_check_text_contains("res://scripts/main.gd", "AtlasTexture.new()", failures)
	_check_text_contains("res://scripts/main.gd", "AnimatedSprite2D", failures)
	_check_text_contains("res://scripts/main.gd", "_show_baekgu_state", failures)
	_check_text_contains("res://scripts/main.gd", "BAEKGU_VISUAL_SCALE", failures)
	_check_text_contains("res://scripts/main.gd", "_add_world_bounds", failures)
	_check_text_contains("res://scripts/main.gd", "HomeSouthHedge", failures)
	_check_text_contains("res://scripts/main.gd", "SafetyFenceRoadBlock", failures)
	_check_text_contains("res://scripts/main.gd", "UpperEscapeLeftBoundary", failures)
	_check_text_contains("res://scripts/main.gd", "RescueNorthRoadblock", failures)
	_check_text_contains("res://scripts/main.gd", "_add_roadside_detail_pass", failures)
	_check_text_contains("res://scripts/main.gd", "_add_store_detail_pass", failures)
	_check_text_contains("res://scripts/main.gd", "StoreShoppingBasket", failures)
	_check_text_contains("res://scripts/main.gd", "FactoryWarningStripe", failures)
	_check_text_contains("res://scripts/main.gd", "RescueTireSkidA", failures)
	_check_text_contains("res://scripts/main.gd", "_add_factory_area", failures)
	_check_text_contains("res://scripts/main.gd", "FactoryExitBlocker", failures)
	_check_text_contains("res://scripts/main.gd", "factory_exit", failures)
	_check_text_contains("res://scripts/main.gd", "dog_intervention", failures)
	_check_text_contains("res://scripts/main.gd", "EXHAUSTED_ESCAPE", failures)
	_check_text_contains("res://scripts/main.gd", "rescue_zone\", Vector2(0, -2225)", failures)
	_check_text_contains("res://scripts/spray_controller.gd", "manager.set_spray_uses(manager.spray_uses - 1)", failures)
	_check_text_contains("res://scripts/autoload/audio_manager.gd", "AudioStreamGenerator", failures)
	_check_text_contains("res://scripts/autoload/audio_manager.gd", "Bgm_EerieDrone", failures)
	_check_text_contains("res://scripts/autoload/audio_manager.gd", "set_bgm_intensity", failures)
	_check_text_contains("res://scripts/autoload/audio_manager.gd", "stream.buffer_length = 0.9", failures)
	_check_text_contains("res://scripts/autoload/audio_manager.gd", "rescue_honk", failures)
	_check_text_contains("res://scripts/autoload/audio_manager.gd", "bush_rustle", failures)
	_check_text_contains("res://scripts/autoload/audio_manager.gd", "phone_ring", failures)
	_check_text_contains("res://scripts/autoload/audio_manager.gd", "dog_bark", failures)
	_check_text_contains("res://scripts/autoload/audio_manager.gd", "metal_clang", failures)
	_check_text_contains("res://scripts/autoload/audio_manager.gd", "rescue_honk_far", failures)
	_check_text_contains("res://scripts/autoload/audio_manager.gd", "player.stop()", failures)
	_check_text_contains("res://scripts/autoload/audio_manager.gd", "player.stream = stream", failures)
	_check_text_contains("res://scripts/autoload/game_manager.gd", "store_receipt", failures)
	_check_text_contains("res://scripts/autoload/game_manager.gd", "STORE_CLUE_IDS", failures)
	_check_text_contains("res://scripts/autoload/game_manager.gd", "STORE_CLUE_LABELS", failures)
	_check_text_contains("res://scripts/autoload/game_manager.gd", "_is_store_investigation_complete", failures)
	_check_text_contains("res://scripts/autoload/game_manager.gd", "_set_bgm_for_stage", failures)
	_check_text_contains("res://scripts/autoload/game_manager.gd", "문은 잊어", failures)
	_check_text_contains("res://scripts/autoload/game_manager.gd", "interaction_prompt_changed", failures)
	_check_text_contains("res://scripts/autoload/game_manager.gd", "set_interaction_prompt", failures)
	_check_text_contains("res://scripts/autoload/game_manager.gd", "FACTORY_CHASE_DURATION := 40", failures)
	_check_text_contains("res://scripts/autoload/game_manager.gd", "DOG_INTERVENTION", failures)
	_check_text_contains("res://scripts/autoload/game_manager.gd", "FACTORY_CHASE", failures)
	_check_text_contains("res://scripts/autoload/game_manager.gd", "finish_factory_timer", failures)
	_check_text_contains("res://scripts/autoload/game_manager.gd", "start_exhausted_escape", failures)
	_check_text_contains("res://scripts/hud.gd", "interaction_label", failures)
	_check_text_contains("res://data/dialogues.json", "store_footprints", failures)
	_check_text_contains("res://data/dialogues.json", "store_payphone", failures)
	_check_text_contains("res://data/dialogues.json", "store_clues_complete", failures)
	_check_text_contains("res://data/dialogues.json", "dog_intervention", failures)
	_check_text_contains("res://data/dialogues.json", "factory_hide", failures)
	_check_text_contains("res://data/dialogues.json", "exhausted_escape", failures)
	_check_text_contains("res://data/dialogues.json", "백구가 괴물의 앞을 가로막고", failures)
	_check_text_contains("res://tools/validate_extended_flow.gd", "EXTENDED_FLOW_OK", failures)
	_check_text_contains("res://tools/validate_extended_flow.gd", "start_dog_intervention", failures)
	_check_text_contains("res://tools/validate_extended_flow.gd", "factory_chase_seconds_left == manager.FACTORY_CHASE_DURATION", failures)
	_check_text_contains("res://tools/validate_extended_flow.gd", "FACTORY_CHASE_SPEED > main.player.walk_speed", failures)
	_check_text_contains("res://tools/validate_extended_flow.gd", "_factory_obstacle_count", failures)
	_check_text_contains("res://tools/validate_extended_flow.gd", "start_exhausted_escape", failures)
	_check_text_contains("res://tools/validate_map_bounds.gd", "MAP_BOUNDS_OK", failures)
	_check_text_absent("res://scripts/main.gd", "store_sensor", failures)
	_check_text_absent("res://scripts/main.gd", "SensorClueGlint", failures)
	_check_text_absent("res://scripts/autoload/game_manager.gd", "store_sensor", failures)
	_check_text_absent("res://data/dialogues.json", "\"store_sensor\"", failures)

	if failures.size() > 0:
		for failure in failures:
			print("VALIDATION_FAIL: ", failure)
		quit(1)
	print("VALIDATION_OK")
	quit(0)

func _check_file(path: String, failures: Array[String]) -> void:
	if not FileAccess.file_exists(path):
		failures.append("missing file: " + path)

func _check_resource_load(path: String, failures: Array[String]) -> void:
	var resource = load(path)
	if resource == null:
		failures.append("cannot load resource: " + path)

func _check_json(path: String, failures: Array[String]) -> void:
	if not FileAccess.file_exists(path):
		return
	var file := FileAccess.open(path, FileAccess.READ)
	if file == null:
		failures.append("cannot open json: " + path)
		return
	var parsed = JSON.parse_string(file.get_as_text())
	if parsed == null:
		failures.append("cannot parse json: " + path)

func _check_text_contains(path: String, needle: String, failures: Array[String]) -> void:
	if not FileAccess.file_exists(path):
		return
	var file := FileAccess.open(path, FileAccess.READ)
	if file == null:
		return
	if not file.get_as_text().contains(needle):
		failures.append("missing expected text in " + path + ": " + needle)

func _check_text_absent(path: String, needle: String, failures: Array[String]) -> void:
	if not FileAccess.file_exists(path):
		return
	var file := FileAccess.open(path, FileAccess.READ)
	if file == null:
		return
	if file.get_as_text().contains(needle):
		failures.append("unexpected text in " + path + ": " + needle)
